cmake_minimum_required(VERSION 3.21)
project(EtherNet LANGUAGES C CXX ASM)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR)
    message(FATAL_ERROR "Use the standalone build preset, not an in-source build.")
endif()
find_package(Python3 REQUIRED COMPONENTS Interpreter)
list(APPEND CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake")
include(MakeNso)
include(FpicExternal)
configure_file(linkerscripts/application.ld application.ld COPYONLY)
configure_file(linkerscripts/syms.ld syms.ld COPYONLY)
set(SKYLAUNCH_LINKERSCRIPTS_DIR ".")
configure_file(linkerscripts/switch.specs.in switch.specs @ONLY)
add_subdirectory(vendor/glm)
add_subdirectory(vendor/fmt)
add_subdirectory(vendor/tomlpp)
add_subdirectory(vendor/magic_enum)
set(IMGUI_XENO_EXTERNAL_TOOLCHAIN TRUE)
add_subdirectory(vendor/imgui-xeno)
ethernet_external_fpic(imgui_xeno)
ethernet_external_fpic(fmt)
target_compile_definitions(imgui_xeno PUBLIC IMGUI_XENO_LOAD_DEFAULT_FONT=false)
add_subdirectory(src)
